### ISSUE TITLE
Sending Mail fails when using SparkPost SMTP

### ISSUE THREAD

**Issue by nianurag** [pankleks/pm2-health#16]
As no "from" field is included and `user` field `form` are not same for this SMTP gateway.
Can I submit the fix?

**Comment by pankleks** [comment]
added to 1.7.3, let me know if works ok

**Comment by nianurag** [comment]
Thanks :)
How do I install this specific version `1.7.3`? 
Looks like you haven't published the module with these changes so confused.

**Comment by pankleks** [comment]
it's released to npm, to install/update use `pm2 install pm2-health`

**Comment by nianurag** [comment]
It works, I got confused earlier as the config didn't have `from` field. Please add it in the config and mark this as resolved.

**Comment by pankleks** [comment]
`from` field is optional, that's why it's not added to config. It's mentioned in readme.
