### ISSUE TITLE
No emails are going out on test

### ISSUE THREAD

**Issue by vqalex** [pankleks/pm2-health#25]
Hi,

I can't make it to work, basically it everything installs, I added smtp.gmail.com and the rest of the stuff. When I trigger email test, it is not going out at all, not even hitting smtp.gmail.com..are there anything else needs to be done? I'm using  node js 8.11.3, latest PM2 and everything is on Ubuntu.

**Comment by pankleks** [comment]
@vqalex could you please test on latest version 1.10.1, thanks

**Comment by pankleks** [comment]
@vqalex if does not work still, please use  version 1.9.5

**Comment by vqalex** [comment]
Thank you, I will test tonight

**Comment by vqalex** [comment]
latest doesn't work, but 1.9.5 works

**Comment by Shirazhussain** [comment]
@pankleks how install 1.9.5 version?

**Comment by vqalex** [comment]
Add @1.9.5

**Comment by vqalex** [comment]
pm2 install pm2-health@1.9.5
