### ISSUE TITLE
App is inactive

### ISSUE THREAD

**Issue by chhatch** [pankleks/pm2-health#32]
Every since I upgraded pm2-health to v1.11.8 pm2-health-out.log is being filled with the message "app is inactive". The message is correct because the server is just waiting for requests, but I'm getting way too many messages. I'm getting that message 3 times (at the same time) every minute, which is odd because I only have 1 instance of my app and pm2 -health running. It's making pm2-health's output in `pm2 logs` useless because it's just a bunch of copies of the same message.

Reading the documentation I don't see any obvious way to handle this problem. Thanks for any assistance you can provide.

**Comment by pankleks** [comment]
closing as should be fixed
